### ISSUE TITLE
[breaking change]Cleanup: Remove the start workflow API with ObjectWorkflow parameter

### ISSUE THREAD

**Issue by longquanzheng** [indeedeng/iwf-java-sdk#187]
The one using `final Class<? extends ObjectWorkflow> workflowClass`  being used 99.99%. 

The idea behind `ObjectWorkflow` one turns out not that useful. 

We could delete them to avoid confusing. And potentially, change `doStartWorkflow` to `startWorkflow` and become public as the most generic/raw form of start workflow

**Comment by zklgame** [comment]
I am wondering whether it will bring another confusion to users after making the `doStartWorkflow` method to be public to call. 

Because users now have to maintain the parameter `wfType` passed into the new public method the same as what defined in the `ObjectWorkflow.getWorkflowType()` method.

So the new usage will be like:
```
wf = new XXXWorkflow();
client.startWorkflow(wf.getWorkflowType(), wfId, ...)
```
or

```
String wfType = "XXX";
client.startWorkflow(wfType, wfId, ...)

// and users have to explicitly override the getWorkflowType() method now:
public class XXXWorkflow implements ObjectWorkflow {
    String getWorkflowType() {
        return wfType;
    }
}
```

To avoid confusion, maybe we should not make the `doStartWorkflow ` public, and also delete the getWorkflowType() method in the ObjectWorkflow interface?

**Comment by zklgame** [comment]
Actually, if a user explicitly overrides the `getWorkflowType()` method in the Workflow Class, and starts workflows by `final Class<? extends ObjectWorkflow> workflowClass`, there will be `IllegalArgumentException`.

The same issue also exists in the State class.

**Comment by zklgame** [comment]
In #195
